const DB : Dictionary = {
	0: {
		"Name": "Nivar",
		"Attacks": [10,20,30],
		"MaxDefense": 30,
		"MaxHealth": 60,
		"SpecialMove": "Thunderclap",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Esmuri",
	},
	1: {
		"Name": "Urzagrim",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 40,
		"SpecialMove": "Barrage",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Eneter",
	},
	2: {
		"Name": "Aineira",
		"Attacks": [30,40,50],
		"MaxDefense": 70,
		"MaxHealth": 10,
		"SpecialMove": "Shackle",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Sannoque",
	},
	3: {
		"Name": "Ruhiel",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 30,
		"SpecialMove": "Betrayal",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Menrath",
	},
	4: {
		"Name": "Elete",
		"Attacks": [40,50,60],
		"MaxDefense": 50,
		"MaxHealth": 60,
		"SpecialMove": "Transform",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Siven",
	},
	5: {
		"Name": "Myteus",
		"Attacks": [40,50,60],
		"MaxDefense": 60,
		"MaxHealth": 50,
		"SpecialMove": "Scorch",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Ozionor",
	},
	6: {
		"Name": "Hetros",
		"Attacks": [10,20,30],
		"MaxDefense": 20,
		"MaxHealth": 60,
		"SpecialMove": "Eclipse",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Gethor",
	},
	7: {
		"Name": "Oulyte",
		"Attacks": [30,40,50],
		"MaxDefense": 70,
		"MaxHealth": 30,
		"SpecialMove": "Whirlwind",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Urax",
	},
	8: {
		"Name": "Tabris",
		"Attacks": [20,30,40],
		"MaxDefense": 30,
		"MaxHealth": 40,
		"SpecialMove": "Slice",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Bruqur",
	},
	9: {
		"Name": "Gadriel",
		"Attacks": [10,20,30],
		"MaxDefense": 10,
		"MaxHealth": 70,
		"SpecialMove": "Seism",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Qeamas",
	},
	10: {
		"Name": "Ylos",
		"Attacks": [30,40,50],
		"MaxDefense": 60,
		"MaxHealth": 10,
		"SpecialMove": "Dispel",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Shogara",
	},
	11: {
		"Name": "Betrios",
		"Attacks": [40,50,60],
		"MaxDefense": 60,
		"MaxHealth": 50,
		"SpecialMove": "Fury",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Runo",
	},
	12: {
		"Name": "Vanor",
		"Attacks": [40,50,60],
		"MaxDefense": 50,
		"MaxHealth": 40,
		"SpecialMove": "Burst",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Dukura",
	},
	13: {
		"Name": "Dhalnape",
		"Attacks": [30,40,50],
		"MaxDefense": 60,
		"MaxHealth": 10,
		"SpecialMove": "Sunder",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Fagren",
	},
	14: {
		"Name": "Sanotah",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 40,
		"SpecialMove": "Salvo",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Luphis",
	},
	15: {
		"Name": "Linzos",
		"Attacks": [10,20,30],
		"MaxDefense": 30,
		"MaxHealth": 70,
		"SpecialMove": "Bane",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Vaelas",
	},
	16: {
		"Name": "Istramath",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 30,
		"SpecialMove": "Blight",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Ezanir",
	},
	17: {
		"Name": "Zulron",
		"Attacks": [30,40,50],
		"MaxDefense": 60,
		"MaxHealth": 20,
		"SpecialMove": "Blizzard",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Likira",
	},
	18: {
		"Name": "Jurlug",
		"Attacks": [40,50,60],
		"MaxDefense": 70,
		"MaxHealth": 30,
		"SpecialMove": "Purge",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Nahel",
	},
	19: {
		"Name": "Fulmez",
		"Attacks": [10,20,30],
		"MaxDefense": 20,
		"MaxHealth": 50,
		"SpecialMove": "Bolt",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Kiohlore",
	}
}
