const DB : Dictionary = {
	0: {
		"Name": "Nivar",
		"Attacks": [10,20,30],
		"MaxDefense": 30,
		"MaxHealth": 60,
		"SpecialMove": "Thunderclap",
		"SpecialMoveDesc": "[p align=center]Rolls a random [img=16]res://cards/assets/suits/Spades64.png[/img] Spade in your hand.[/p]",
		"PointValue": 900,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Esmuri",
	},
	1: {
		"Name": "Urzagrim",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 40,
		"SpecialMove": "Barrage",
		"SpecialMoveDesc": "[p align=center]Locks up to 3 [img=16]res://cards/assets/suits/Hearts64.png[/img] Hearts in your hand for 1 move.[/p]",
		"PointValue": 600,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Eneter",
	},
	2: {
		"Name": "Aineira",
		"Attacks": [30,40,50],
		"MaxDefense": 70,
		"MaxHealth": 10,
		"SpecialMove": "Shackle",
		"SpecialMoveDesc": "[p align=center]Locks the highest [img=16]res://cards/assets/suits/Hearts64.png[/img] Heart in your hand for 3 moves.[/p]",
		"PointValue": 800,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Sannoque",
	},
	3: {
		"Name": "Ruhiel",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 30,
		"SpecialMove": "Betrayal",
		"SpecialMoveDesc": "[p align=center]Rolls the highest card in your hand.[/p]",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Menrath",
	},
	4: {
		"Name": "Elete",
		"Attacks": [40,50,60],
		"MaxDefense": 50,
		"MaxHealth": 60,
		"SpecialMove": "Transform",
		"SpecialMoveDesc": "[p align=center]Rolls the highest [img=16]res://cards/assets/suits/Clubs64.png[/img] Club in your hand.[/p]",
		"PointValue": 1100,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Siven",
	},
	5: {
		"Name": "Myteus",
		"Attacks": [40,50,60],
		"MaxDefense": 60,
		"MaxHealth": 50,
		"SpecialMove": "Scorch",
		"SpecialMoveDesc": "[p align=center]Locks up to 2 [img=16]res://cards/assets/suits/Clubs64.png[/img] Clubs in your hand for 1 move.[/p]",
		"PointValue": 1100,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Ozionor",
	},
	6: {
		"Name": "Hetros",
		"Attacks": [10,20,30],
		"MaxDefense": 20,
		"MaxHealth": 60,
		"SpecialMove": "Eclipse",
		"SpecialMoveDesc": "[p align=center]Rolls the lowest [img=16]res://cards/assets/suits/Diamonds64.png[/img] Diamond in your hand.[/p]",
		"PointValue": 800,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Gethor",
	},
	7: {
		"Name": "Oulyte",
		"Attacks": [30,40,50],
		"MaxDefense": 70,
		"MaxHealth": 30,
		"SpecialMove": "Whirlwind",
		"SpecialMoveDesc": "[p align=center]Rolls up to 4 [img=16]res://cards/assets/suits/Diamonds64.png[/img] Diamonds in your hand.[/p]",
		"PointValue": 1000,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Urax",
	},
	8: {
		"Name": "Tabris",
		"Attacks": [20,30,40],
		"MaxDefense": 30,
		"MaxHealth": 40,
		"SpecialMove": "Slice",
		"SpecialMoveDesc": "[p align=center]Locks the highest [img=16]res://cards/assets/suits/Spades64.png[/img] Spade in your hand for 3 moves.[/p]",
		"PointValue": 700,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Bruqur",
	},
	9: {
		"Name": "Gadriel",
		"Attacks": [10,20,30],
		"MaxDefense": 10,
		"MaxHealth": 70,
		"SpecialMove": "Seism",
		"SpecialMoveDesc": "[p align=center]Rolls 3 random cards in your hand.[/p]",
		"PointValue": 800,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Qeamas",
	},
	10: {
		"Name": "Ylos",
		"Attacks": [30,40,50],
		"MaxDefense": 60,
		"MaxHealth": 10,
		"SpecialMove": "Dispel",
		"SpecialMoveDesc": "[p align=center]Rolls the 2 lowest [img=16]res://cards/assets/suits/Hearts64.png[/img] Hearts in your hand.[/p]",
		"PointValue": 700,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Shogara",
	},
	11: {
		"Name": "Betrios",
		"Attacks": [40,50,60],
		"MaxDefense": 60,
		"MaxHealth": 50,
		"SpecialMove": "Fury",
			"SpecialMoveDesc": "[p align=center]Locks all [img=16]res://cards/assets/suits/Clubs64.png[/img] Clubs in your hand for 3 moves.[/p]",
		"PointValue": 1100,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Runo",
	},
	12: {
		"Name": "Vanor",
		"Attacks": [40,50,60],
		"MaxDefense": 50,
		"MaxHealth": 40,
		"SpecialMove": "Burst",
		"SpecialMoveDesc": "[p align=center]Rolls the 3 highest [img=16]res://cards/assets/suits/Diamonds64.png[/img] Diamonds in your hand.[/p]",
		"PointValue": 900,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Dukura",
	},
	13: {
		"Name": "Dhalnape",
		"Attacks": [30,40,50],
		"MaxDefense": 60,
		"MaxHealth": 10,
		"SpecialMove": "Sunder",
		"SpecialMoveDesc": "[p align=center]Locks the 3 lowest cards in your hand for 3 moves.[/p]",
		"PointValue": 700,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Fagren",
	},
	14: {
		"Name": "Sanotah",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 40,
		"SpecialMove": "Salvo",
		"SpecialMoveDesc": "[p align=center]Rolls the 3 lowest cards in your hand.[/p]",
		"PointValue": 600,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Luphis",
	},
	15: {
		"Name": "Linzos",
		"Attacks": [10,20,30],
		"MaxDefense": 30,
		"MaxHealth": 70,
		"SpecialMove": "Bane",
		"SpecialMoveDesc": "[p align=center]Rolls all [img=16]res://cards/assets/suits/Hearts64.png[/img] Hearts in your hand.[/p]",
		"PointValue": 1000,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Vaelas",
	},
	16: {
		"Name": "Istramath",
		"Attacks": [20,30,40],
		"MaxDefense": 20,
		"MaxHealth": 30,
		"SpecialMove": "Blight",
		"SpecialMoveDesc": "[p align=center]Rolls all [img=16]res://cards/assets/suits/Clubs64.png[/img] Clubs in your hand.[/p]",
		"PointValue": 500,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Ezanir",
	},
	17: {
		"Name": "Zulron",
		"Attacks": [30,40,50],
		"MaxDefense": 60,
		"MaxHealth": 20,
		"SpecialMove": "Blizzard",
		"SpecialMoveDesc": "[p align=center]Locks all [img=16]res://cards/assets/suits/Diamonds64.png[/img] Diamonds in your hand for 3 moves.[/p]",
		"PointValue": 800,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Likira",
	},
	18: {
		"Name": "Jurlug",
		"Attacks": [40,50,60],
		"MaxDefense": 70,
		"MaxHealth": 30,
		"SpecialMove": "Purge",
		"SpecialMoveDesc": "[p align=center]Rolls all cards in your hand.[/p]",
		"PointValue": 1000,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Nahel",
	},
	19: {
		"Name": "Fulmez",
		"Attacks": [10,20,30],
		"MaxDefense": 20,
		"MaxHealth": 50,
		"SpecialMove": "Bolt",
		"SpecialMoveDesc": "[p align=center]Locks all [img=16]res://cards/assets/suits/Spades64.png[/img] Spades in your hand for 2 moves.[/p]",
		"PointValue": 700,
		"Portrait": "res://assets/ui/CardSilhouette.png",
		"Stage": "Kiohlore",
	}
}
